name: our-mahjong-history

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    working_dir: /workspace
    volumes:
      - ..:/workspace
      - /var/run/docker.sock:/var/run/docker.sock
    network_mode: host
    environment:
      NODE_ENV: development
      WATCHPACK_POLLING: "true"
      CHOKIDAR_USEPOLLING: "true"
    stdin_open: true
    tty: true
    command: sleep infinity
